"""Evidence-backed feature coverage; Complete means local workflow, not service certification."""
FEATURES = [
    ('Shows','Configured storage roots and free space','Library Locations','Complete','library_locations.py, library_storage.py: add/default/remove unused roots; protect roots used by shows.'),
    ('Shows','Choose destination when adding shows','Search / Trakt','Complete','show_destination.js: configured root chooser and destination preview.'),
    ('Shows','Edit show folder and preferences','Show Detail / Library','Complete','show_preferences.py: typed profile IDs, pause, language, statuses, subtitle and numbering options.'),
    ('Shows','Browse shows and episodes','Show Queue / Show Detail','Complete','manager.js, show_detail.js: paging, filtering and episode detail.'),
    ('Shows','Import SickChill library','Import Center','Partial','sickchill_importer.py: imports show/episode data; not every upstream configuration field is translated.'),
    ('Shows','Save add-show preferences as defaults','Edit Show Settings / Add Show','Complete','show_preferences.py: save defaults without changing existing shows; Search and Trakt add routes inherit them.'),
    ('Episodes','Bulk episode status management','Manage Center','Complete','episode_rules.py and sickchill_parity.py: preview/apply episode changes.'),
    ('Episodes','Specials / Season 00 control','Show Detail / Settings','Complete','episode_rules.py: ignored specials excluded from search and missing counts.'),
    ('Search','Manual and backlog episode search','Show Detail / Missing','Partial','engine.py: search and scoring implemented; live provider behavior needs validation.'),
    ('Search','Date, sports and scene searches','Show Settings / Advanced','Partial','show_preferences.py: date and stored scene numbering used in provider requests; manual and cached XEM mapping sources are supported.'),
    ('Search','Anime and automatic XEM mapping','Advanced','Partial','scene_sync.py: cached XEM refresh after metadata refresh, manual override precedence and reverse matching. Live XEM returned HTTP 403 in this environment; aliases/group rules and complete multi-mapping search remain partial.'),
    ('Search','Native SickChill provider roster','Providers','Partial','Generic Newznab/Torznab adapters do not implement upstream site-specific login, cookies and scraping. See upstream inventory.'),
    ('Downloads','Client handoff and queue monitoring','Download Center','Partial','engine.py and downloader_polling.py: SAB/qBittorrent plus NZBGet/Transmission/Deluge polling. Other upstream clients remain missing. Live credentials/clients needed for end-to-end checks.'),
    ('Downloads','Failed download history and retry','Manage Center','Partial','Failure records and retry workflows exist; automatic recovery needs live client validation.'),
    ('Post processing','Preview and approve completed files','Post Processing','Complete','engine.py: matched/blocked/unmatched review and explicit approval before processing.'),
    ('Post processing','Naming and season folders','Naming / Show Settings','Complete','naming.py: configured naming and per-show flat/season folders.'),
    ('Post processing','Archive extraction and extra scripts','Post Processing','Missing','No complete SickChill-compatible archive extraction and post-processing script workflow.'),
    ('Post processing','Rename existing library in place','Show Detail / Library','Complete','library_rename.py: signed preview, selected approval, no overwrite, sidecars, multi-episode grouping, rollback and recovery journals.'),
    ('Metadata','TMDb refresh and language','Show Settings','Partial','metadata_service.py: per-show language and default new-episode statuses; requires TMDb configuration.'),
    ('Metadata','TVDB / AniDB as primary indexers','Metadata Sources / Add Show','Partial','tvdb_client.py implements TVDB v4 search and refresh for new shows. AniDB and existing-library source migration remain missing; live TVDB credentials required.'),
    ('Metadata','DVD episode ordering','TVDB Add Show','Partial','New TVDB shows can choose aired/DVD order. Existing-library order migration is not implemented. Live TVDB validation is outstanding.'),
    ('Metadata','NFO and artwork format coverage','Metadata','Partial','Metadata/artwork routines exist; full upstream format and consumer compatibility are not verified.'),
    ('Subtitles','Automatic subtitle search and per-show switch','Subtitles / Show Settings','Partial','sync.py and production.py: OpenSubtitles adapter and per-show opt-out; upstream subtitle-provider coverage is incomplete.'),
    ('Notifications','Native notification services','Notification Services','Partial','notifiers.py: native Discord, Slack, Telegram, Gotify, Pushover and Pushbullet event delivery. Other upstream adapters remain missing; live delivery is unverified.'),
    ('Media servers','Plex / Kodi / Emby / Jellyfin updates','Media Servers','Partial','Configuration and refresh integrations require live server validation; not all upstream behaviors are covered.'),
    ('Automation','Scheduled jobs and mutual exclusion','Jobs / Settings','Partial','scheduler_guard.py: UTC leases and atomic acquisition; every scheduled external workflow is not yet certified.'),
    ('Operations','Logs, job status and diagnostics','Logs / Jobs / System','Complete','Local status, progress and diagnostic workflows implemented.'),
    ('Safety','Backup and restore','Database Safety','Partial','Backup validation and recovery guidance exist; native complete restore workflow is missing.'),
    ('Help','In-app workflow guidance','Help Center','Complete','help_content.py: searchable guides and explicit coverage gaps.'),
]
